WIP: Implement `plotResidualsVsTime()`
Open-Systems-Pharmacology/OSPSuite-R pull request #1002
Opened 2022-06-15 08:48 UTC by IndrajeetPatil

TODO

- [ ] Implement residuals calculation function
- [ ] Implement `plotResidualsVsTime()`
- [ ] tests for `plotResidualsVsTime()` 
- [ ] check comments

Related to #674 

Discussed in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/discussions/811

Closes #803 
Closes #925

2022-07-21 14:08 UTC, IndrajeetPatil commented
Here is what the default plot looks like:

```r
library(ospsuite)

# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

# import observed data (will return a list of DataSet objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)

# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal"
  )
)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal",
    "Stevens_2012_placebo.Placebo_total",
    "Stevens_2012_placebo.Placebo_distal",
    "Stevens_2012_placebo.Placebo_proximal"
  ),
  groups = c("Solid total", "Solid distal", "Solid proximal", "Solid total", "Solid distal", "Solid proximal")
)

# create plot config
myPC <- DefaultPlotConfiguration$new()
myPC$legendPosition <- tlf::LegendPositions$outsideRight

# plot
plotResidualsVsTime(myCombDat, myPC)
```

![obs_vs_pred](https://user-images.githubusercontent.com/11330453/180232728-5fd1fdf3-7c18-42ff-9d2a-27c2ab594b48.png)

2022-07-22 08:35 UTC, IndrajeetPatil commented
And here is what the default `plotResidualsVsSimulated()` output looks like:

```r
library(ospsuite)

# load the simulation
sim <- loadTestSimulation("MinimalModel")
simResults <- importResultsFromCSV(
  simulation = sim,
  filePaths = getTestDataFilePath("Stevens_2012_placebo_indiv_results.csv")
)

# import observed data (will return a list of DataSet objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)

# create a new instance and add datasets
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)
myCombDat$addSimulationResults(
  simResults,
  quantitiesOrPaths = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal"
  )
)

myCombDat$setGroups(
  names = c(
    "Organism|Lumen|Stomach|Metformin|Gastric retention",
    "Organism|Lumen|Stomach|Metformin|Gastric retention distal",
    "Organism|Lumen|Stomach|Metformin|Gastric retention proximal",
    "Stevens_2012_placebo.Placebo_total",
    "Stevens_2012_placebo.Placebo_distal",
    "Stevens_2012_placebo.Placebo_proximal"
  ),
  groups = c("Solid total", "Solid distal", "Solid proximal", "Solid total", "Solid distal", "Solid proximal")
)

# default
plotResidualsVsSimulated(myCombDat)
```

![obs_vs_pred](https://user-images.githubusercontent.com/11330453/180399101-dd091089-b38e-47a8-a0f3-2eac988024cd.png)

2022-07-22 09:08 UTC, PavelBal commented
> Here is what the default plotResidualsVsTime() output looks like:

X-axis values (or units) can't be right ;)

2022-07-22 09:51 UTC, PavelBal requested changes
Small changes.

I did not review the code, just from the user perspective.

2022-07-22 09:51 UTC, PavelBal commented on NEWS.md
> +    - `plotObservedVsSimulated()` for observed versus predicted data scatter plot.
"for observed versus simulated..." to be consistent with function naming.

2022-07-22 09:51 UTC, PavelBal commented on NEWS.md
> +    - `plotResidualsVsSimulated()` for predicted versus residuals data scatter plot.
as above - simulated instead of predicted.

2022-07-22 09:52 UTC, PavelBal commented
Could you add to this commit to NEWS.MD:

- The class `SimulationBatch` gets a new property `id`
- The output of `runSimulationBatches()` is now a named list with names being the ids of `SimulationBatch`

2022-07-22 09:55 UTC, IndrajeetPatil commented
Okay, updated NEWS to address all of the above-mentioned points.

2022-07-22 09:58 UTC, PavelBal approved these changes

2022-07-22 09:58 UTC, PavelBal commented
Please let someone else review the code before merging (until for a while).

2022-07-22 09:58 UTC, IndrajeetPatil commented
Yepp, we do need at least 2 approvals on this one.

2022-07-22 18:13 UTC, Yuri05 approved these changes

2022-07-22 18:18 UTC, merged