Data transformations set by partial calls now retain previous values
Open-Systems-Pharmacology/OSPSuite-R pull request #1145
Opened 2022-09-27 16:40 UTC by svavil

Closes #1120 . Added a corresponding test.

2022-09-27 16:43 UTC, svavil commented
@PavelBal I'm only pushing changes with this pull request that are related to data transformations. Hopefully they will work fine in the develop branch, but I've only tested them with the 11.1.15 core.

2022-09-28 07:44 UTC, PavelBal requested changes

2022-09-28 07:44 UTC, PavelBal commented on R/data-combined.R
> +        if (any(!missing(xOffsets), !missing(yOffsets), !missing(xScaleFactors), !missing(yScaleFactors))) {
I wonder if you require this line at all...

2022-09-28 08:25 UTC, PavelBal approved these changes

2022-09-28 08:25 UTC, merged