update core
Open-Systems-Pharmacology/OSPSuite-R pull request #1379
Opened 2024-03-25 10:45 UTC by rwmcintosh

2024-03-25 21:21 UTC, PavelBal approved these changes

2024-03-26 09:48 UTC, Felixmil requested changes
This hotfix/11.3 contains very old code that is unsynced with `develop`. 
1. Is hotfix/11.3 really the target branch ?
2. If so, shouldn't hotfix/11.3 be updated with `develop` content ?

2024-03-26 09:53 UTC, Yuri05 commented
> This hotfix/11.3 contains very old code that is unsynced with `develop`.
> 
>     1. Is hotfix/11.3 really the target branch ?
> 
>     2. If so, shouldn't hotfix/11.3 be updated with `develop` content ?

1: yes 
2: no

The version is synced with the upcoming 11.3 hotfix release of the OSP suite and should not get any newer v12 features from the develop branch.

2024-03-26 10:16 UTC, Felixmil commented
How to handle the fact that this version is not compatible with latest versions of `{tlf}` ? I mean that this branch does not work in an updated environment. Shall we add fixed versions entries in DESCRIPTION ?

2024-03-26 11:57 UTC, Felixmil commented on DESCRIPTION
I add fixed package versions corresponding to the AppVeyor's installation script for this release.
Necessary because some breaking changes were included in tlf without backward compatibility.

2024-03-26 12:13 UTC, merged

2024-03-26 13:10 UTC, Yuri05 commented
@rwmcintosh I retriggered manualy the nightly build and it failed
```
rake "prepare_for_build[%APPVEYOR_BUILD_VERSION%, 'hotfix/11.3']"
C:/projects/ospsuite-r/rakefile.rb:9: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
rake aborted!
OpenURI::HTTPError: 404 Not Found
```

Do we really need `''` in `'hotfix/11.3'` ?

2024-03-26 13:12 UTC, rwmcintosh commented
yeah, maybe not. I'll change it